name: build kernel
on: push
jobs:
  build:
    name: Build
    runs-on: mhmmdfdlyas/dockerfile:k
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
        with:
          path: sources
          submodules: true

      - name: clone stuff
        run: |
            git clone -j$(nproc --all) -b rvc-inline https://github.com/greenforce-project/kernel_xiaomi_citrus_sm6115 kernel && \
            cd kernel && git fetch origin && git reset --hard
            git clone -j$(nproc --all) --single-branch https://github.com/fadlyas07/anykernel-3 --depth=1 
            git clone -j$(nproc --all) --single-branch https://github.com/Inkypen79/arm64-gcc-9.3 --depth=1
            git clone -j$(nproc --all) --single-branch https://github.com/ztotherad/arm32-gcc --depth=1

      - name: do build
        run: |
            cd $(pwd)/kernel
            source ../kernel_env.sh
            source ../tg_upload.sh
            bash ../kernel_env.sh $cid $bot $mid
            msg "Build started ..."
            build_start=$(date +"%s")
            export PATH="$(pwd)/arm64-gcc-9.3/bin:$(pwd)/arm32-gcc/bin:$PATH"
            build_env="ARCH=arm64 CROSS_COMPILE_COMPAT=arm-eabi- CROSS_COMPILE=aarch64-elf-"
            make -j$(nproc --all) -l$(nproc --all) -C $(pwd) O=out $build_env vendor/juice-perf_defconfig
            make -j$(nproc --all) -l$(nproc --all) -C $(pwd) O=out $main_env 2>&1| tee build.log
            if ! [[ -f $(pwd)/out/arch/arm64/boot/Image ]] ; then
                CAPT_TEXT="Build failed bro, build under $branch branch. Pls check the log ASAP!"
                tg file build.log telegram_personal_id $CAPT_TEXT
                notif "$CAPT_TEXT"
              exit 1 ;
            else
                if [[ -e $(pwd)/out/.config ]] ; then
                    cp $(pwd)/out/.config regen_defconfig
                    tg file regen_defconfig telegram_personal_id
                else
                    CAPT_TEXT="Bruh .config not found, cannot regenerate defconfig."
                    notif "$CAPT_TEXT" && msg "$CAPT_TEXT"
                fi
            fi
            info
            build_end=$(date +"%s")
            build_diff=$(($build_end - $build_start))
            build_diff_msg="$(($build_diff / 60)) minutes, $(($build_diff % 60)) seconds"
            CAPT_TEXT="Build success after ${build_diff_msg}. Now we will making flashable zip ..."
            notif "$CAPT_TEXT" && tg file build.log telegram_personal_id $CAPT_TEXT
            mv $(pwd)/out/arch/arm64/boot/Image $(pwd)/anykernel-3
            cd anykernel-3 && zip -r9 GF-juice-weekly-$(TZ=Asia/Jakarta date +'%H%M-%d%m%y').zip * && cd ..
            tg file $(echo $(pwd)/anykernel-3/*.zip) telegram_personal_id $caption_template
